### ISSUE TITLE
Add toggle for CRT mode on and off

### ISSUE THREAD

**Issue by ainslec** [mattiasgustavsson/dos-like#21]
Hi,

Currently F11 toggles between full screen and windowed, but it might be also nice to be able to toggle the crt mode off. I find the crt mode works with some screens well, and on lower res screens, it can lead to a kind of banding effect. I guess this is down to non integer scaling? Just guessing. Anyway, a toggle would help.

Chris

**Comment by mattiasgustavsson** [comment]
For dos-like, I wouldn’t want the CRT on a toggle, as I think the CRT effect is a key part of its look-and-feel. But of course, anyone who wants to make a fork which has a toggle is free to do so. It is quite straightforward, just don’t do the calls to crtemu_pc_present here https://github.com/mattiasgustavsson/dos-like/blob/ff62f874813afed024505c906166e466ffe9d1fe/source/dos.h#L3154
And instead change the call to app_present to pass screen_xbgr, width, height, instead of NULL, 1, 1,
There might be some videomodes that looks a bit odd though, as one of the things the CRT mode does is stretch to a 4:3 aspect ratio regardless of screen buffer size

it might be possible to fix the banding issues of the CRT shader though, but I am not sure what they are, I have not come across them myself
