### ISSUE TITLE
Can't lower volume using media keys when running dos-like compiled executable

### ISSUE THREAD

**Issue by ainslec** [mattiasgustavsson/dos-like#22]
I was running a dos like game (stranded) and it was really loud, but I found that my volume up and volume down buttons on my keyboard did not work. This is the first time something like this has happened with my keyboard in 5 years of having it. Not sure how easy it is to test if you don't have media buttons on your own keyboard. 

Just reporting it here in case it helps the project.

**Comment by mattiasgustavsson** [comment]
I think this is because I am registering listeners for the media keys in app.h
https://github.com/mattiasgustavsson/dos-like/blob/ff62f874813afed024505c906166e466ffe9d1fe/source/libs/app.h#L2136
This is something that was merged in from changes for another project using app.h. I should probably put this on an optional switch. Maybe I’ll just remove those lines for now, dos-like don’t use them anyway.

**Comment by mattiasgustavsson** [comment]
I believe this should be fixed now in the latest version
